### ISSUE TITLE
CSS Nesting with BEM

### ISSUE THREAD

**Issue by jonnybarnes** [what1s1ove/whatislove.dev#678]
I’m not sure if it works as intended?

Here’s a minimal example where there are two buttons, and one is rendered bigger than the other.

Notice the “parent” class is `.button`, and in the HTML the actual class I added was `.foo--prim`. But it still gets the primary style added, in this case an even larger font size, but could be anything:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>CSS Nesting</title>
    <style>
      .button {
        font-size: 2rem;

        &[class*='--prim'] {
          font-size: 3rem;
        }
      }
    </style>
  </head>
  <body>
    <div>
      <button
        type="button"
        class="button"
      >
        Save
      </button>
    </div>

    <div>
      <button
        type="button"
        class="button foo--prim"
      >
        Update
      </button>
    </div>
  </body>
</html>
```

**Comment by what1s1ove** [comment]
Hi @jonnybarnes ! Thank you for your comment! It works as you described! The button size will be 3 rem.

Yes, using class attributes to describe modifiers is quite risky if you are unaware of all the intricacies, for example as you mentioned. I am sure there are many others.

But honestly, using two modifiers from different blocks with the same name is a rather rare occurrence. At least, it hasn't happened in my practice.

Overall, the point of the article is to share my experience and possibly inspire someone to try something new. However, I definitely wouldn't want it to become a standard for anyone. People need to understand all the risks.
